// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarCode from "./navbar.js";
// import Link from "next/link";

import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter', 
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        < NavbarCode />
        {children}
      </body>
    </html>
  );
}
